version: "3.3"

services:
  vf:  
    container_name: videofetcher
    build:
      context: .
    image: vf-bot
    restart: always
    volumes:
      #- /tmp/videofetcher:/code/output_dir
      - ./videofetcher:/code

